name: bookstore_app
description: "A Well Organized E-Comerce Book Shop! Made with love for Book Worms :D"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  hugeicons: ^0.0.7
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_fonts: ^6.2.1
  toastification: ^2.3.0
  awesome_bottom_bar: ^1.2.4
  cloud_firestore: ^5.5.0
  flutter_native_splash: ^2.4.3
  lorem_ipsum: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
